### ISSUE TITLE
small discrepancy; the terms "horizontally/vertically" have the opposite names compared to image editing software.

### ISSUE THREAD

**Issue by echo-lalia** [dfaker/SD-latent-mirroring#11]
Hey! I wanna start out by saying that I don't mean to nitpick, I just wanted to share this feedback because I like this extension and will likely be using it regularly. Plus, any solution to this problem would likely be relatively easy to fix, compared to usual bugfixes.

**The problem, in more detail:** Image editing programs like Photoshop, Clip Studio Paint, and all others that I have used, use the terms "horizontal" and "vertical" mirroring to describe the inverse operation, relative to this extension; usually mirroring something horizontally means to mirror it along the vertical axis, so that the left becomes the right, and vice versa (left->right, horizontal direction). And, mirroring something vertically means to mirror it along the horizontal axis, so that the top becomes the bottom, and vice versa (top->bottom, vertical direction). This extension reverses those meanings so that horizontal mirroring flips things along the horizon, and vertical mirroring flips things along the vertical axis.

**Suggested solution:** if it were me, I'd probably simply reverse the terms in the software for constancy with other image editing software. But, if you do not want to do that, I think adding some short help text above, (or on hover) the generation options would avoid confusion, too :)

**Comment by dfaker** [comment]
Ha, I can never keep those straight when using image editing software either.

Those are switched around now.
