### ISSUE TITLE
Add zooming and panning options

### ISSUE THREAD

**Issue by prozacgod** [dfaker/SD-latent-mirroring#2]
Forgive me if I missunderstand how this all works, so if this isn't a rational request... 

Could you make an option or perhaps an extension that zooms the latent space in or out, something like this could improve character generation and keep it from cutting off heads and feet.

In addition or alternatively - add the ability to pan the latent space during generation?

**Comment by dfaker** [comment]
Zooming in is possible, I'm not sure what you'd 'fill' the empty sections with when you were panning or zooming out though.

**Comment by prozacgod** [comment]
with panning you could fill one side with the data from the other side, probably wierd artifacts be abound, but interested to try?

**Comment by prozacgod** [comment]
zooming out you could just leave the original  do that same thing I guess, not sure if it would have the desired effect.

**Comment by dfaker** [comment]
Zooming didn't do anything useful, the output was denoised totally differently than the original.
Panning was sort of useful at least at low values, so that's added in now, update to give it a go.

**Comment by dtlnor** [comment]
maybe we could tile it before zooming out?

**Comment by dfaker** [comment]
> maybe we could tile it before zooming out?

I tried a number of mechanisms for padding from torchvision.transforms.Pad none of them maintained anything like the original image, at at guess it looks like the interpolation for downsizing them is destructive to any denoising progress already made and it basically restarts - we also know that the denoising is trained on a specific scale so it makes seems the coherency after scaling would be poor.
