### ISSUE TITLE
Add a toggle for flip direction?

### ISSUE THREAD

**Issue by slashedstar** [dfaker/SD-latent-mirroring#4]
So you can flip from right to left, down to up, etc.

**Comment by dfaker** [comment]
Is this not what mirror style is doing, vertical being left/right and horizontal being up/down?

**Comment by slashedstar** [comment]
Yeah, the toggle is so it does in the opposite direction, to flip down to up instead of up to down, and right to left instead of left to right (vertical flipping might not be much meaningful but horizontal one would allow to mirror the floor instead of the sky)

**Comment by dfaker** [comment]
It's not actually mirroring any given half of the image, it's either flipping on alternate steps, or averaging both flipped and unflipped versions - the fact that the sky is at the top is still down to the network being trained on skies at the top - there's no orientation preferred in the 'latent-mirroring' process itself.

**Comment by slashedstar** [comment]
I see, I thought it mirrored one half, it just flips the entire thing. 👍
