### ISSUE TITLE
Any way to use this with Highres Fix

### ISSUE THREAD

**Issue by azureprophet** [dfaker/SD-latent-mirroring#8]
Hi there! Is there any way to use this with highres fix where it won't apply to the second round? When applied to the second round it makes the image blurry and slightly doubled and thus doesn't work well. Thanks again for your wonderful extension!

**Comment by HardeNNN** [comment]
This please, right now it messes up the highres fix...

**Comment by dfaker** [comment]
Needs some indication from Automatic111 that it's in a HR pass, offered in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6781

**Comment by HardeNNN** [comment]
> Needs some indication from Automatic111 that it's in a HR pass, offered in [AUTOMATIC1111/stable-diffusion-webui#6781](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6781)

so should we expect an update soon? I'd do it myself but am not really familiar with how A1111 works

**Comment by HardeNNN** [comment]
bump

**Comment by NBEM** [comment]
bump
